#!/usr/bin/env bash

# Go to root
cd "$(git rev-parse --git-dir)" && cd ..

npm install
bundle install --quiet
bundle exec jekyll build --trace

## bundle audit
# bundle-audit update
# bundle-audit check # --update flag doesn't work
## htmlproof URLs
# bundle exec htmlproof --check-html _site/
# htmlhint
htmlhint _site
# scss-lint
bundle exec scss-lint static/css/*.scss
# SASS check
bundle exec sass -c static/css/style.scss
## jscs
# jscs static/js/
## jshint
# jshint static/js/
## csslint
# csslint static/css/style.css --exclude-list=""
# kwalify link .yml
bundle exec kwalify -lf .link-lint.yml data/links/da.yml && bundle exec kwalify -lf .link-lint.yml data/links/en.yml
# mdl
mdl -c .mdlrc _posts/*.markdown _posts/*/*.markdown ./*.md
## Git
git diff --check # Show whitespace errors
