#!/usr/bin/env bash

# Go to root
cd $(git rev-parse --git-dir) && cd ..

bundle exec jekyll build --trace

## htmlproof URLs
# bundle exec htmlproof _site/ # --check-html
# htmlhint
htmlhint _site
# scss-lint
bundle exec scss-lint static/css/*.scss
# jscs
jscs static/js/
## jshint
# jshint static/js/
## csslint
# csslint static/css/style.css --exclude-list=""
# mdl
mdl -c .mdlrc _posts/*.markdown _posts/*/*.markdown *.md

