type: seq
sequence:
    - type: map
      mapping:
        title:
        #   length:
            #   min: 1
            #   max: 65
            required: yes
            type: str
            unique: yes
        date:
            pattern: "/(0[1-9]|[12][0-9]|3[01])\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s(20[1-9][1-9])/"
            required: yes
        url:
            required: yes
            unique: yes
