exclude: "_site/"

linters:
  BangFormat:
    enabled: true
  BorderZero:
    enabled: false
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  Compass::*:
    enabled: false  # Change?
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: false  # Subjective
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: true
    style: short
  HexNotation:
    enabled: true
    style: uppercase  # Subjective
  HexValidation:
    enabled: true
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  Indentation:
    enabled: false  # Disabled for extra indentaiton
    width: 4  # Subjective
    character: spaces
  LeadingZero:
    enabled: true
  NameFormat:
    enabled: false  # Subjective
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: false  # Subjective
  PropertySpelling:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false  # Subjective
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAfterPropertyName:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
    style: double_quotes  # Subjective
  TrailingSemicolon:
    enabled: true
  TrailingZero:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: tur
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: true
