sudo: false

language: node_js
node_js:
  - 5.10.1

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

before_install:
  - rvm install 2.2.0-dev
# - brew update

install:
  - bundle install --verbose
  - npm install
# - brew install shellcheck # && brew tap homebrew/dupes && brew install homebrew/dupes/tidy --HEAD

before_script:
  - node -v && npm -v
  - ruby -v
  - cat Gemfile.lock
# - bundle outdated
# - bundle exec bundle-audit check # Returns error code on fail

script:
  - bundle exec jekyll build --profile --trace

after_script:
# - bundle exec htmlproofer --check-html --file-ignore=$HTML_EXCLUDES $HTML_FOLDER
  - htmlhint $HTML_FOLDER
# - tidy -config .tidy-config && tidy -e -q $HTML_FOLDER/index.html
  - stylelint $STYLE_FOLDER/*.scss --syntax scss
  - bundle exec sass -c static/css/style.scss
  - jscs $JS_FOLDER
  - jshint $JS_FOLDER
  - bundle exec kwalify -lf .link-lint.yml data/links/da.yml && bundle exec kwalify -lf .link-lint.yml data/links/en.yml
  - shellcheck _resources/pre-commit
  - markdownlint _posts/*.markdown _posts/*/*.markdown *.md

notifications:
  email:
    on_success: change
    on_failure: always
