sudo: false

language: ruby
rvm:
  - 2.2.0-dev

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

before_install:
# - brew update

install:
  - bundle install --verbose
  - npm install
# - brew install shellcheck # && brew tap homebrew/dupes && brew install homebrew/dupes/tidy --HEAD

before_script:
  - cat Gemfile.lock
# - bundle outdated
  - bundle-audit update

script:
  - bundle exec jekyll build --profile --trace

after_script:
  - bundle-audit check
  - bundle exec htmlproofer --check-html --file-ignore=$HTML_EXCLUDES $HTML_FOLDER
  - htmlhint $HTML_FOLDER
# - tidy -config .tidy-config && tidy -e -q $HTML_FOLDER/index.html
  - bundle exec scss-lint $STYLE_FOLDER/*.scss
  - bundle exec sass -c static/css/style.scss
  - csslint --format=compact --quiet --exclude-list=$CSS_EXCLUDES $CSS_FILES
  - csslint --quiet --errors=bulletproof-font-face,gradients,fallback-colors,text-indent --exclude-list=$CSS_EXCLUDES $CSS_FILES
  - jscs $JS_FOLDER
  - jshint $JS_FOLDER
  - bundle exec kwalify -lf .link-lint.yml data/links/da.yml && bundle exec kwalify -lf .link-lint.yml data/links/en.yml
  - shellcheck _resources/pre-commit
  - gem install --quiet mdl && mdl -c .mdlrc _posts/*.markdown _posts/*/*.markdown *.md

notifications:
  email:
    on_success: change
    on_failure: always
