language: ruby

rvm:
  - 1.9.3

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

install:
  - bundle install --quiet
  - npm install

before_script:
  - cat Gemfile.lock
# - bundle outdated

script:
  - bundle exec jekyll build --trace

after_script:
  - htmlproof --validate_html --file_ignore=$HTML_EXCLUDES $HTML_FOLDER
  - htmlhint $HTML_FOLDER
  - bundle exec scss-lint $STYLE_FOLDER/*.scss
  - csslint $CSS_FILES --exclude-list=$CSS_EXCLUDES
  - jscs $JS_FOLDER
  - jshint $JS_FOLDER
  - gem install mdl & mdl _posts/*.markdown -c .mdlrc

notifications:
  email:
    on_success: change
    on_failure: always
