language: ruby

rvm:
  - 1.9.3

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

install:
  - bundle install --verbose
  - npm install
# - brew update && brew tap homebrew/dupes && brew install homebrew/dupes/tidy --HEAD

before_script:
  - cat Gemfile.lock
# - bundle outdated

script:
  - bundle exec jekyll build --trace

after_script:
  - htmlproof --check-html --file-ignore=$HTML_EXCLUDES $HTML_FOLDER
  - htmlhint $HTML_FOLDER
# - tidy -config .tidy-config && tidy -e -q $HTML_FOLDER/index.html
  - bundle exec scss-lint $STYLE_FOLDER/*.scss
  - csslint $CSS_FILES --exclude-list=$CSS_EXCLUDES
  - jscs $JS_FOLDER
  - jshint $JS_FOLDER
  - gem install --quiet mdl && mdl -c .mdlrc _posts/*.markdown _posts/*/*.markdown *.md

notifications:
  email:
    on_success: change
    on_failure: always
