name: Hafnia Times
url: https://hafniatimes.com
shorturl: http://hafnia.co
repo:  https://github.com/hafniatimes/hafniatimes.github.io
dyslexia_support: true
data_source: data

# Settings # # # # # # # # # # #
ga:               "UA-7184031-12"
github_hosted:    true
show_footer:      true
status_bar_color: false
 # # # # # # # # # # # # # # # #

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
permalink: pretty
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values: &en_defaults
            layout: "post"
            author: "ndarville"
            lang: "en"
            categories: "articles"
    -
        scope: # busted
            path: "_posts/da"
        values: &da_defaults
            lang: "da"
            categories:
                - "da"
                - "articles"
#   - # Redundant when top scope path is ""
#       scope: # busted
#           path: "_drafts"
#       values: *en_defaults
    -
        scope: # busted
            path: "_drafts/da"
        values: *da_defaults

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.md"
    - "README.md"
    - "STYLE.md"
    - "WRITERS.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"

sass:
    sass_dir: static/css/
    sourcemap: :auto
    style: :nested

translations:
    _atom:
        da: "Alle danske artikler"
        en: "All English articles"
    _dates:
        da:
            months:
                jan: "Januar"
                feb: "Februar"
                mar: "Marts"
                apr: "April"
                may: "Maj"
                jun: "Juni"
                jul: "Juli"
                aug: "August"
                sep: "September"
                oct: "Oktober"
                nov: "November"
                dec: "December"
            weekdays:
                mon: "Mandag"
                tue: "Tirsdag"
                wed: "Onsdag"
                thu: "Torsdag"
                fri: "Fredag"
                sat: "Lørdag"
                sun: "Søndag"
    _languages:
        da:
            da: "Dansk"
            en: "Engelsk"
        en:
            da: "Danish"
            en: "English"
    navigation:
        da:
            code: "Kode"
            dyslexia: "Ordblindhed"
            feed: "RSS"
            home: "Forside"
        en:
            code: "Code"
            dyslexia: "Dyslexia"
            feed: "Feed"
            home: "Home"
    footer:
        da:
            shorturl: "Korturl"
            dyslexia_credit: "Ordblindefont fra"
        en:
            shorturl: "Shorturl"
            dyslexia_credit: "Dyslexia font from"
    frontpage:
        da:
            articles: "Artikler"
            description: "En dansk udgivelse på engelsk, som advokerer for åben data og gennemsigtighed i teknologi og politik."
            linked_articles: "Nyheder I Andre Medier"
            who: "Hvem Vi Er"
        en:
            articles: "Articles"
            description: "A Danish publication in English promoting open data and transparency in tech and politics."
            linked_articles: "News in Other Media"
            who: "Who We Are"
    post:
        da:
            by: "Af"
            read: "Læs på dansk"
            translation: "Oversættelse af"
            update_text: "Dette indlæg er blevet opdateret, siden det blev udgivet. Se alle ændringer"
            update_link: "hér"
        en:
            by: "By"
            read: "Read in English"
            translation: "Translation by"
            update_text: "This post has been updated, since it was first published. View all changes"
            update_link: "here"

languages: &languages
    - name:  "English"
      value: "en"
    - name:  "Dansk"
      value: "da"

locale:
    da: "da_DK"
    en: "en_GB"

prose:
    siteurl: "https://hafniatimes.com"
  # rooturl: "/"
  # media: "assets/"
    metadata:
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: title # Field available in place of filename input
              field:
                  label: Title
                  element: text
                  value: ""
            - name: excerpt
              field:
                  label: Excerpt/Description/Summary
                  help: Used for the Twitter Card summary
                  placeholder: Use 200 characters at most
                  element: textarea
                  value: ""
            - name: slug
              field:
                  label: URL Slug
                  element: text
                  value: ""
            - name: author
              field:
                  label: Author
                  help: Use your GitHub username
                  element: text
                  value: ""
            - name: guest
              field:
                  label: Guest
                  help: Is the author a guest contributor with no GitHub account?
                  value: false
                  element: checkbox
            - name: "date"
              field:
                  label: "Date"
                  help: "Use 24h notation"
                  placeholder: "YYYY-MM-DD HH:MM:SS"
                  element: "text"
                  value: "CURRENT_DATETIME"
            - name: updated
              field:
                  label: Updated
                  help: Have significant edits been made to the article since publication?
                  value: false
                  element: checkbox
            - name: lang
              field:
                  label: Language
                  help: The language of the post
                  placeholder: English
                  element: select
                  options: *languages
                  selected: en
            - name: translator
              field:
                  label: Translator
                  help: (Other) person who translated the original article
                  element: text
                  value: ""
            - name: trans
              field:
                  label: Translation
                  help: URL for translated version of article
                  element: text
                  value: ""
            - name: categories
              field:
                  label: Categories
                  element: hidden
                  value: article
    ignore:
        - _config.yml
        - .csslintrc
        - .gitignore
        - .htaccess
        - .jscsrc
        - .jshintrc
        - .mdlrc
        - .ruby-version
        - .scss-lint.yml
        - .tidyrc
        - .travis.yml
        - _favicon.ico
        - CNAME
        - DICTIONARY.md
        - favicon.ico
        - feed.atom
        - Gemfile
        - identicon.png
        - index.html
        - LICENSE.md
        - package.json
        - README.md
        - sitemap.xml
        - STYLE.md
        - STYLE.da.md
        - WRITERS.md
        - /_layouts
        - /_includes
        - /_resources
        - /404
        - /da
        - /en
        - /static
