name: Hafnia Times
description: A Danish publication in English promoting open data and transparency in tech and politics.
url:   http://hafniatimes.com
repo:  https://github.com/hafniatimes/hafniatimes.github.io
ga:   "UA-XXXXXXXX-Y"

github_hosted: true

show_footer: false

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.md"
    - "README.md"
    - "WRITERS.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"

sass:
    sass_dir: static/css/
    style: :nested

prose:
    siteurl: "http://hafniatimes.com"
    metadata:
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: author
              field:
                  label: Author
                  help: Use your GitHub username
                  element: text
                  value: ""
            - name: title
              field:
                  label: Title
                  element: text
                  value: ""
            - name: date
              field:
                  label: Date
                  help: Use 24-hour notation
                  placeholder: YYYY-MM-DD HH:MM:SS
                  element: text
                  value: ""
            - name: excerpt
              field:
                  label: Excerpt/Description/Summary
                  help: Used for the Twitter Card summary
                  placeholder: Use 200 characters at most.
                  element: text
                  value: ""
            - name: slug
              field:
                  label: URL Slug
                  element: text
                  value: ""
                  alterable: true
            - name: categories
              field:
                  label: Categories
                  element: hidden
                  value: article
            - name: updated
              field:
                  label: Updated
                  help: Has the article been edited since its publication?
                  value: false
                  element: checkbox
    ignore:
        - _config.yml
        - .csslintrc
        - .gitignore
        - .htaccess
        - .scss-lint.yml
        - .travis.yml
        - _favicon.ico
        - CNAME
        - favicon.ico
        - feed.atom
        - Gemfile
        - identicon.png
        - index.html
        - LICENSE.md
        - package.json
        - README.md
        - WRITERS.md
        - /_layouts
        - /_includes
        - /404
        - /static
