name: Hafnia Times
description: A Danish publication in English promoting open data and transparency in tech and politics.
url:   http://hafniatimes.com
repo:  https://github.com/hafniatimes/hafniatimes.github.io
ga:   "UA-7184031-12"

github_hosted: true

show_footer: false

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.md"
    - "README.md"
    - "WRITERS.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"

sass:
    sass_dir: static/css/
    style: :nested

translations:
    _atom:
        da: "Alle danske artikler"
        en: "All English articles"
    _dates:
        da:
            months:
                jan:  "Januar"
                feb:  "Februar"
                mar:  "Marts"
                apr:  "April"
                may:  "Maj"
                jun:  "Juni"
                jul:  "Juli"
                aug:  "August"
                sep:  "September"
                oct: "Oktober"
                nov: "November"
                dec: "December"
            weekdays:
                mon: "Mandag"
                tue: "Tirsdag"
                wed: "Onsdag"
                thu: "Torsdag"
                fri: "Fredag"
                sat: "Lørdag"
                sun: "Søndag"
    navigation:
        da:
            code: "Kildekode"
            feed: "RSS"
            home: "Forside"
        en:
            code: "Code"
            feed: "Feed"
            home: "Home"
    frontpage:
        da:
            articles: "Artikler"
            description: "En dansk udgivelse på engelsk, som advokerer for åben data og gennemsigtighed i teknologi og politik."
            who: "Hvem Vi Er"
        en:
            articles: "Articles"
            description: "A Danish publication in English promoting open data and transparency in tech and politics."
            who: "Who We Are"
    post:
        da:
            by: "Af"
            update_text: "Dette indlæg er blevet opdateret, siden det blev udgivet. Se alle ændringer"
            update_link: "hér"
        en:
            by: "By"
            update_text: "This post has been updated, since it was first published. View all changes"
            update_link: "here"

languages: &languages
    - name:  "English"
      value: "en"
    - name:  "Dansk"
      value: "da"
prose:
    siteurl: "http://hafniatimes.com"
    metadata:
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: author
              field:
                  label: Author
                  help: Use your GitHub username
                  element: text
                  value: ""
            - name: Guest
              field:
                  label: Guest
                  help: Is the author a guest contributor with no GitHub account?
                  value: false
                  element: checkbox
            - name: title
              field:
                  label: Title
                  element: text
                  value: ""
            - name: date
              field:
                  label: Date
                  help: Use 24-hour notation
                  placeholder: YYYY-MM-DD HH:MM:SS
                  element: text
                  value: ""
            - name: excerpt
              field:
                  label: Excerpt/Description/Summary
                  help: Used for the Twitter Card summary
                  placeholder: Use 200 characters at most
                  element: text
                  value: ""
            - name: slug
              field:
                  label: URL Slug
                  element: text
                  value: ""
                  alterable: true
            - name: lang
              field:
                  label: Language
                  help: The language of the post
                  placeholder: English
                  element: select
                  options: *languages
                  selected: en
            - name: categories
              field:
                  label: Categories
                  element: hidden
                  value: article
            - name: updated
              field:
                  label: Updated
                  help: Has the article been edited since its publication?
                  value: false
                  element: checkbox
        # _posts/da:
        #     - name: categories
        #       field:
        #           label: Categories
        #           element: hidden
        #           value:
        #               - da
        #               - article
    ignore:
        - _config.yml
        - .csslintrc
        - .gitignore
        - .htaccess
        - .scss-lint.yml
        - .travis.yml
        - _favicon.ico
        - CNAME
        - favicon.ico
        - feed.atom
        - Gemfile
        - identicon.png
        - index.html
        - LICENSE.md
        - package.json
        - README.md
        - WRITERS.md
        - /_layouts
        - /_includes
        - /_resources
        - /404
        - /da
        - /static
