name: "Hafnia Times"
url:   http://hafniatimes.com
ga:   "UA-XXXXXXXX-Y"

github_hosted: true

show_footer: false

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE.md"
    - "README.md"
    - "WRITERS.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"

sass:
    sass_dir: static/css/
    style: :nested

prose:
    siteurl: "http://hafniatimes.com"
    metadata:
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: author
              field:
                  label: Author
                  help: Use your GitHub username
                  element: text
                  value: ""
            - name: title
              field:
                  label: Title
                  element: text
                  value: ""
            - name: date
              field:
                  label: Date
                  help: Use 24-hour notation
                  placeholder: YYYY-MM-DD HH:MM:SS
                  element: text
                  value: ""
            - name: excerpt
              field:
                  label: Excerpt/Description/Summary
                  help: Used for the Twitter Card summary
                  placeholder: Use 200 characters at most.
                  element: text
                  value: ""
            - name: slug
              field:
                  label: URL Slug
                  element: text
                  value: ""
                  alterable: true
            - name: categories
              field:
                  label: Categories
                  element: hidden
                  value: article
            - name: updated
              field:
                  label: Updated
                  help: Has the article been edited since its publication?
                  value: false
                  element: checkbox
    ignore:
        - _config.yml
        # - favicon.ico
        # - CNAME
        # - feed.atom
        # - Gemfile
        # - identicon.png
        - README.md
        # - index.html
        - /_layouts
        - /_includes
        - /404
        - /static
