name: Hafnia Times
url: https://hafniatimes.com
shorturl: http://hafnia.co
repo: https://github.com/hafniatimes/hafniatimes.github.io
data_dir: data
timezone: Europe/Copenhagen

# Settings # # # # # # # # # # #
dyslexia_support: true
ga:               "UA-7184031-12"
github_hosted:    true
show_footer:      true
 # # # # # # # # # # # # # # # #

# Visual Config # # # # #
web_app_enabled:  false
web_app_title:    ""
status_bar_color: false
apple_icon_sizes:
    - "76x76"
    - "120x120"
    - "152x152"
    - "180x180"
# # # # # # # # # # # # #

# Posts # # # # # #
html5_images: true
show_posts: true
show_bylines: true
limit_posts: 0
permalink: pretty
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    auto_id_prefix: h-
    auto_id_stripping: false
    auto_ids: true
    footnote_backlink: "&#8617;&#65038;"
    input: GFM
    syntax_highlighter: rouge
    toc_levels: 3..6
highlighter: rouge
 # # # # # # # # # # # # # # # # # # # # # # # # #

gems:
#   - jekyll-compose
    - jekyll-sitemap
    - jekyll-redirect-from

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values: &en_defaults
            layout: "post"
            author: "ndarville"
            lang: "en"
            categories: "articles"
    -
        scope: # busted
            path: "_posts/da"
        values: &da_defaults
            lang: "da"
            categories:
                - "da"
                - "articles"
#   - # Redundant when top scope path is ""
#       scope: # busted
#           path: "_drafts"
#       values: *en_defaults
    -
        scope: # busted
            path: "_drafts/da"
        values: *da_defaults

exclude:
    - ".*" # Automatic, but just in case
    - "*.log"
    - "*.md"
    - "Gemfile*"
    - "identicon.png"
    - "package.json"
    - "data/links/"
    - "node_modules/"

sass:
    sass_dir: static/css/
    sourcemap: :auto
    style: :nested

translations:
    _dates:
        da:
            months:
                jan: "Januar"
                feb: "Februar"
                mar: "Marts"
                apr: "April"
                may: "Maj"
                jun: "Juni"
                jul: "Juli"
                aug: "August"
                sep: "September"
                oct: "Oktober"
                nov: "November"
                dec: "December"
            weekdays:
                mon: "Mandag"
                tue: "Tirsdag"
                wed: "Onsdag"
                thu: "Torsdag"
                fri: "Fredag"
                sat: "Lørdag"
                sun: "Søndag"
    _feed:
        da: "Alle danske artikler"
        en: "All English articles"
    _languages:
        da:
            da: "Dansk"
            en: "Engelsk"
        en:
            da: "Danish"
            en: "English"
    _links:
        da: "Andre danske artikler om Danmark"
        en: "Other English articles on Denmark"
    404:
        da:
            title: "Side Ikke Fundet (404)"
            text: "Siden du søgte fandtes ikke her. Beklager meget."
        en:
            title: "Page Not Found (404)"
            text: "The page you were looking for is not here. Sorry."
    navigation:
        da:
            code: "Kode"
            dyslexia: "Ordblind"
            feed: "RSS"
            home: "Forside"
        en:
            code: "Code"
            dyslexia: "Dyslexic"
            feed: "Feed"
            home: "Home"
    footer:
        da:
            shorturl: "Korturl"
            dyslexia_credit: "Ordblindefont fra"
        en:
            shorturl: "Shorturl"
            dyslexia_credit: "Dyslexia font from"
    frontpage:
        da:
            articles: "Artikler"
            description: "En dansk udgivelse på engelsk, som advokerer for åben data og gennemsigtighed i teknologi og politik."
            linked_articles: "Nyheder I Andre Medier"
            who: "Hvem Vi Er"
        en:
            articles: "Articles"
            description: "A Danish publication in English promoting open data and transparency in tech and politics."
            linked_articles: "News in Other Media"
            who: "Who We Are"
    post:
        da:
            by: "Af"
            read: "Læs på dansk"
            translation: "Oversættelse af"
            update_text: "Indlægget er blevet opdateret siden udgivelsen. Se alle ændringer"
            update_link: "hér"
        en:
            by: "By"
            read: "Read in English"
            translation: "Translation by"
            update_text: "This post has been updated since its publication. View all changes"
            update_link: "here"

languages: &languages
    - name:  "English"
      value: "en"
    - name:  "Dansk"
      value: "da"

prose:
    siteurl: "https://hafniatimes.com"
  # rooturl: "/"
  # media: "assets/"
    metadata:
        _posts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: title # Field available in place of filename input
              field:
                  label: Title
                  element: text
                  value: ""
            - name: excerpt
              field:
                  label: Excerpt/Description/Summary
                  help: Used for the Twitter Card summary
                  placeholder: Use 200 characters at most
                  element: textarea
                  value: ""
            - name: slug
              field:
                  label: URL Slug
                  element: text
                  value: ""
            - name: author
              field:
                  label: Author
                  help: Use your GitHub username
                  element: text
                  value: ""
            - name: guest
              field:
                  label: Guest
                  help: Is the author a guest contributor with no GitHub account?
                  value: false
                  element: checkbox
            - name: "date"
              field:
                  label: "Date"
                  help: "Use 24h notation"
                  placeholder: "YYYY-MM-DD HH:MM:SS"
                  element: "text"
                  value: "CURRENT_DATETIME"
            - name: updated
              field:
                  label: Updated
                  help: Have significant edits been made to the article since publication?
                  value: false
                  element: checkbox
            - name: lang
              field:
                  label: Language
                  help: The language of the post
                  placeholder: English
                  element: select
                  options: *languages
                  selected: en
            - name: translator
              field:
                  label: Translator
                  help: (Other) person who translated the original article
                  element: text
                  value: ""
            - name: trans
              field:
                  label: Translation
                  help: URL for translated version of article
                  element: text
                  value: ""
            - name: categories
              field:
                  label: Categories
                  element: hidden
                  value: article
    ignore:
        - _config.yml
        - .csslintrc
        - .gitattributes
        - .gitignore
        - .htaccess
        - .jscsrc
        - .jshintrc
        - .link-lint.yml
        - .mdlrc
        - .ruby-version
        - .scss-lint.yml
        - .tidyrc
        - .travis.yml
        - _favicon.ico
        - CNAME
        - DICTIONARY.md
        - favicon.ico
        - favicon.png
        - feed.atom
        - Gemfile
        - identicon.png
        - index.html
        - LICENSE.md
        - links.atom
        - package.json
        - README.md
        - sitemap.xml
        - STYLE.md
        - STYLE.da.md
        - WRITERS.md
        - /_contact
        - /_layouts
        - /_includes
        - /_resources
        - /404
        - /assets
        - /da
        - /en
        - /static
